sudo: required
dist: trusty

install:
  - sudo apt-get install -y qt5-default qttools5-dev-tools #install necessary Qt files

script:
  - |
    for path in tests/auto/*; do
      [ -d "${path}" ] || continue # if not a directory, skip
      dirname="$(basename "${path}")"
      qmake "CONFIG+=test" tests/auto/$dirname/$dirname.pro
      make
      ./$dirname #run unit test
    done
