#############################################################################
# Makefile for building: Jamtaba
# Generated by qmake (3.0) (Qt 5.5.0)
# Project:  Jamtaba.pro
# Template: subdirs
# Command: E:\Qt\qt\qtbase\bin\qmake.exe -spec win32-msvc2013 -o Makefile Jamtaba.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = E:\Qt\qt\qtbase\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-VstScanner


sub-VstScanner-qmake_all:  FORCE
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	cd VstScanner\ && $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && $(MAKE) -f Makefile qmake_all
sub-VstScanner: FORCE
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile
sub-VstScanner-make_first-ordered: FORCE
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile 
sub-VstScanner-make_first: FORCE
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile 
sub-VstScanner-all-ordered: FORCE
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile all
sub-VstScanner-all: FORCE
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile all
sub-VstScanner-clean-ordered: FORCE
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile clean
sub-VstScanner-clean: FORCE
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile clean
sub-VstScanner-distclean-ordered: FORCE
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-VstScanner-distclean: FORCE
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile distclean
sub-VstScanner-install_subtargets-ordered: FORCE
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile install
sub-VstScanner-install_subtargets: FORCE
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile install
sub-VstScanner-uninstall_subtargets-ordered: FORCE
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-VstScanner-uninstall_subtargets: FORCE
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: Jamtaba.pro ..\..\..\Qt\qt\qtbase\mkspecs\win32-msvc2013\qmake.conf ..\..\..\Qt\qt\qtbase\mkspecs\features\spec_pre.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\common\msvc-desktop.conf \
		..\..\..\Qt\qt\qtbase\mkspecs\qconfig.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_core.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_core_private.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_gui.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_network.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_network_private.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_opengl.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_opengl_private.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_openglextensions.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_openglextensions_private.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_platformsupport_private.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_sql.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_testlib.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_widgets.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_xml.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_qgenericbearer.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_qico.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_qminimal.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_qnativewifibearer.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_qoffscreen.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_qwindows.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_windowsprintersupport.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_tool_qdoc.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_tool_qlalr.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_tool_syncqt.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_tool_uic.pri \
		..\..\..\Qt\qt\qtbase\mkspecs\features\qt_functions.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\qt_config.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\win32\qt_config.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\win32-msvc2013\qmake.conf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\spec_post.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\exclusive_builds.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\default_pre.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\win32\default_pre.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\resolve_config.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\exclusive_builds_post.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\default_post.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\win32\rtti.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\c++11.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\precompile_header.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\warn_on.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\win32\windows.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\testcase_targets.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\exceptions.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\yacc.prf \
		..\..\..\Qt\qt\qtbase\mkspecs\features\lex.prf \
		Jamtaba.pro
	$(QMAKE) -spec win32-msvc2013 -o Makefile Jamtaba.pro
..\..\..\Qt\qt\qtbase\mkspecs\features\spec_pre.prf:
..\..\..\Qt\qt\qtbase\mkspecs\common\msvc-desktop.conf:
..\..\..\Qt\qt\qtbase\mkspecs\qconfig.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_core.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_gui.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_network.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_sql.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_xml.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_qgenericbearer.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_qico.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_qminimal.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_qnativewifibearer.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_qoffscreen.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_qtuiotouchplugin.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_qwindows.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_plugin_windowsprintersupport.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_tool_qdoc.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_tool_qlalr.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_tool_syncqt.pri:
..\..\..\Qt\qt\qtbase\mkspecs\modules\qt_tool_uic.pri:
..\..\..\Qt\qt\qtbase\mkspecs\features\qt_functions.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\qt_config.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\win32\qt_config.prf:
..\..\..\Qt\qt\qtbase\mkspecs\win32-msvc2013\qmake.conf:
..\..\..\Qt\qt\qtbase\mkspecs\features\spec_post.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\exclusive_builds.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\default_pre.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\win32\default_pre.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\resolve_config.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\exclusive_builds_post.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\default_post.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\win32\rtti.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\c++11.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\precompile_header.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\warn_on.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\win32\windows.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\testcase_targets.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\exceptions.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\yacc.prf:
..\..\..\Qt\qt\qtbase\mkspecs\features\lex.prf:
Jamtaba.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2013 -o Makefile Jamtaba.pro

qmake_all: sub-VstScanner-qmake_all FORCE

make_first: sub-VstScanner-make_first-ordered  FORCE
all: sub-VstScanner-all-ordered  FORCE
clean: sub-VstScanner-clean-ordered  FORCE
distclean: sub-VstScanner-distclean-ordered  FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-VstScanner-install_subtargets-ordered FORCE
uninstall_subtargets: sub-VstScanner-uninstall_subtargets-ordered FORCE

sub-VstScanner-debug_ordered:
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-VstScanner-debug_ordered

sub-VstScanner-release_ordered:
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile release
release: sub-VstScanner-release_ordered

sub-VstScanner-check_ordered:
	@if not exist VstScanner\ mkdir VstScanner\ & if not exist VstScanner\ exit 1
	@set MAKEFLAGS=$(MAKEFLAGS)
	cd VstScanner\ && ( if not exist Makefile $(QMAKE) E:\Jamtaba2\jamtaba2\Client\VstScanner\VstScanner.pro -spec win32-msvc2013 -o Makefile ) && $(MAKE) -f Makefile check
check: sub-VstScanner-check_ordered
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

